import { Dataset, ProductionRecord } from '../types/database';

export const DEFAULT_AUTOMOTIVE_DATASET: Dataset = {
  id: 'ds_automotive_seed_01',
  name: 'Automotive Body Shop & Assembly Line',
  original_filename: 'automotive_assembly.csv',
  file_type: 'text/csv',
  file_size: 2638,
  row_count: 20,
  upload_status: 'completed',
  processing_status: 'completed',
  validation_status: 'valid',
  data_quality_score: 98,
  created_at: '2026-03-01T08:00:00Z',
  updated_at: '2026-03-01T08:00:00Z',
};

export const DEFAULT_AUTOMOTIVE_RECORDS: ProductionRecord[] = [
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Press-101',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 460,
    planned_time: 480,
    operating_time: 420,
    downtime: 60,
    planned_downtime: 15,
    unplanned_downtime: 45,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 45,
    actual_cycle_time: 49,
    total_units: 460,
    good_units: 452,
    defective_units: 8,
    rework: 2,
    downtime_reason: 'Hydraulic Pressure Drop',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Weld-Robot-1',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 455,
    planned_time: 480,
    operating_time: 430,
    downtime: 50,
    planned_downtime: 15,
    unplanned_downtime: 35,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 48,
    actual_cycle_time: 51,
    total_units: 455,
    good_units: 448,
    defective_units: 7,
    rework: 3,
    downtime_reason: 'Weld Tip Spatter Cleaning',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Paint-Booth-1',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 440,
    planned_time: 480,
    operating_time: 390,
    downtime: 90,
    planned_downtime: 30,
    unplanned_downtime: 60,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 46,
    actual_cycle_time: 50,
    total_units: 440,
    good_units: 430,
    defective_units: 10,
    rework: 4,
    downtime_reason: 'Nozzle Clog & Flush',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Assembly-Stn-1',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 435,
    planned_time: 480,
    operating_time: 410,
    downtime: 70,
    planned_downtime: 15,
    unplanned_downtime: 55,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 50,
    actual_cycle_time: 54,
    total_units: 435,
    good_units: 429,
    defective_units: 6,
    rework: 1,
    downtime_reason: 'Fastener Feeder Jam',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'QC-Inspection',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 428,
    planned_time: 480,
    operating_time: 440,
    downtime: 40,
    planned_downtime: 10,
    unplanned_downtime: 30,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 52,
    actual_cycle_time: 56,
    total_units: 428,
    good_units: 425,
    defective_units: 3,
    rework: 0,
    downtime_reason: 'Optical Sensor Misalignment',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Press-101',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 430,
    planned_time: 480,
    operating_time: 400,
    downtime: 80,
    planned_downtime: 20,
    unplanned_downtime: 60,
    changeover_time: 20,
    idle_time: 0,
    ideal_cycle_time: 45,
    actual_cycle_time: 50,
    total_units: 430,
    good_units: 420,
    defective_units: 10,
    rework: 2,
    downtime_reason: 'Die Change & Alignment',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Weld-Robot-1',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 425,
    planned_time: 480,
    operating_time: 415,
    downtime: 65,
    planned_downtime: 20,
    unplanned_downtime: 45,
    changeover_time: 15,
    idle_time: 0,
    ideal_cycle_time: 48,
    actual_cycle_time: 53,
    total_units: 425,
    good_units: 417,
    defective_units: 8,
    rework: 4,
    downtime_reason: 'Fixture Clamping Error',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Paint-Booth-1',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 395,
    planned_time: 480,
    operating_time: 360,
    downtime: 120,
    planned_downtime: 30,
    unplanned_downtime: 90,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 46,
    actual_cycle_time: 52,
    total_units: 395,
    good_units: 382,
    defective_units: 13,
    rework: 5,
    downtime_reason: 'Exhaust Fan Vibration',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Assembly-Stn-1',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 410,
    planned_time: 480,
    operating_time: 395,
    downtime: 85,
    planned_downtime: 20,
    unplanned_downtime: 65,
    changeover_time: 10,
    idle_time: 0,
    ideal_cycle_time: 50,
    actual_cycle_time: 55,
    total_units: 410,
    good_units: 402,
    defective_units: 8,
    rework: 2,
    downtime_reason: 'Material Bin Shortage',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-01',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'QC-Inspection',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 400,
    planned_time: 480,
    operating_time: 420,
    downtime: 60,
    planned_downtime: 15,
    unplanned_downtime: 45,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 52,
    actual_cycle_time: 57,
    total_units: 400,
    good_units: 396,
    defective_units: 4,
    rework: 1,
    downtime_reason: 'Calibration Check',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Press-101',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 470,
    planned_time: 480,
    operating_time: 435,
    downtime: 45,
    planned_downtime: 15,
    unplanned_downtime: 30,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 45,
    actual_cycle_time: 48,
    total_units: 470,
    good_units: 464,
    defective_units: 6,
    rework: 1,
    downtime_reason: 'Minor Stoppage',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Weld-Robot-1',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 462,
    planned_time: 480,
    operating_time: 440,
    downtime: 40,
    planned_downtime: 15,
    unplanned_downtime: 25,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 48,
    actual_cycle_time: 50,
    total_units: 462,
    good_units: 456,
    defective_units: 6,
    rework: 2,
    downtime_reason: 'Wire Feed Resistance',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Paint-Booth-1',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 415,
    planned_time: 480,
    operating_time: 375,
    downtime: 105,
    planned_downtime: 30,
    unplanned_downtime: 75,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 46,
    actual_cycle_time: 51,
    total_units: 415,
    good_units: 404,
    defective_units: 11,
    rework: 4,
    downtime_reason: 'Atomizer Pressure Fluctuation',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'Assembly-Stn-1',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 445,
    planned_time: 480,
    operating_time: 425,
    downtime: 55,
    planned_downtime: 15,
    unplanned_downtime: 40,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 50,
    actual_cycle_time: 53,
    total_units: 445,
    good_units: 440,
    defective_units: 5,
    rework: 1,
    downtime_reason: 'Pneumatic Torque Driver Calibration',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 1',
    line_id: 'Line-A',
    machine_id: 'QC-Inspection',
    product_id: 'Part-X1',
    target_quantity: 500,
    actual_quantity: 438,
    planned_time: 480,
    operating_time: 445,
    downtime: 35,
    planned_downtime: 10,
    unplanned_downtime: 25,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 52,
    actual_cycle_time: 55,
    total_units: 438,
    good_units: 435,
    defective_units: 3,
    rework: 0,
    downtime_reason: 'Label Printer Ribbon Reset',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Press-101',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 445,
    planned_time: 480,
    operating_time: 410,
    downtime: 70,
    planned_downtime: 20,
    unplanned_downtime: 50,
    changeover_time: 15,
    idle_time: 0,
    ideal_cycle_time: 45,
    actual_cycle_time: 49,
    total_units: 445,
    good_units: 436,
    defective_units: 9,
    rework: 2,
    downtime_reason: 'Hydraulic Temperature High',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Weld-Robot-1',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 438,
    planned_time: 480,
    operating_time: 425,
    downtime: 55,
    planned_downtime: 20,
    unplanned_downtime: 35,
    changeover_time: 10,
    idle_time: 0,
    ideal_cycle_time: 48,
    actual_cycle_time: 52,
    total_units: 438,
    good_units: 431,
    defective_units: 7,
    rework: 3,
    downtime_reason: 'Coolant Flow Low',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Paint-Booth-1',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 390,
    planned_time: 480,
    operating_time: 350,
    downtime: 130,
    planned_downtime: 30,
    unplanned_downtime: 100,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 46,
    actual_cycle_time: 53,
    total_units: 390,
    good_units: 376,
    defective_units: 14,
    rework: 6,
    downtime_reason: 'Paint Viscosity Out of Spec',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'Assembly-Stn-1',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 420,
    planned_time: 480,
    operating_time: 405,
    downtime: 75,
    planned_downtime: 20,
    unplanned_downtime: 55,
    changeover_time: 10,
    idle_time: 0,
    ideal_cycle_time: 50,
    actual_cycle_time: 54,
    total_units: 420,
    good_units: 413,
    defective_units: 7,
    rework: 2,
    downtime_reason: 'Harness Routing Delay',
  },
  {
    dataset_id: 'ds_automotive_seed_01',
    date: '2026-03-02',
    shift: 'Shift 2',
    line_id: 'Line-A',
    machine_id: 'QC-Inspection',
    product_id: 'Part-X2',
    target_quantity: 480,
    actual_quantity: 412,
    planned_time: 480,
    operating_time: 430,
    downtime: 50,
    planned_downtime: 15,
    unplanned_downtime: 35,
    changeover_time: 0,
    idle_time: 0,
    ideal_cycle_time: 52,
    actual_cycle_time: 56,
    total_units: 412,
    good_units: 408,
    defective_units: 4,
    rework: 1,
    downtime_reason: 'Barcode Scanner Sync',
  },
];
